name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab # v1.4.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout Repository'
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # v3.0.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3f943b86c9a289f4e632c632695e2e0898d9d67d # v1
